import type {
  Badge,
  Contribution,
  DashboardData,
  LeaderboardEntry,
  LeaderboardSeason,
  LeaderboardSnapshot,
  PullRequestAnalysis,
  Quest,
  ScoreBreakdown,
  UserProfile,
} from "@/types/gitrank";

export const currentSeason: LeaderboardSeason = {
  id: "season-2026-05-week-2",
  name: "May Forge Sprint",
  windowLabel: "May 5 - May 11, 2026",
  startsAt: "2026-05-05T00:00:00.000Z",
  endsAt: "2026-05-11T23:59:59.000Z",
  status: "Active",
  scoringVersion: "v1alpha1",
  promotionRule: "Top 25 in Gold promote toward Platinum review.",
  resetRule: "Weekly XP resets each Monday; total XP and evidence stay preserved.",
  explanation:
    "Season placement uses verified profile snapshots, weekly XP, anti-spam multipliers, and score-event evidence.",
};

const contributions: Contribution[] = [
  {
    id: "pr-241",
    owner: "Ayush3941",
    repo: "gitrank",
    number: 241,
    title: "docs: add runtime database access guide",
    status: "merged",
    category: "Documentation",
    difficultyScore: 71,
    impactScore: 78,
    reviewDepthScore: 68,
    testSignalScore: 34,
    repoWeight: 1.15,
    antiSpamMultiplier: 1,
    xpEarned: 428,
    additions: 184,
    deletions: 29,
    changedFilesCount: 6,
    mergedAt: "2026-05-02T18:40:00.000Z",
    maintainerReviewed: true,
    linkedIssue: true,
    ciPassed: true,
    aiSummary:
      "Documented live database access patterns, safety boundaries, and troubleshooting steps for service operators.",
    evidenceSignals: ["Linked issue", "Maintainer review", "Docs changed", "Operational guidance"],
  },
  {
    id: "pr-233",
    owner: "Ayush3941",
    repo: "gitrank",
    number: 233,
    title: "cleanup: replace legacy Docker client with Moby client",
    status: "merged",
    category: "Infrastructure",
    difficultyScore: 84,
    impactScore: 86,
    reviewDepthScore: 74,
    testSignalScore: 58,
    repoWeight: 1.22,
    antiSpamMultiplier: 0.97,
    xpEarned: 612,
    additions: 149,
    deletions: 102,
    changedFilesCount: 11,
    mergedAt: "2026-04-27T11:00:00.000Z",
    maintainerReviewed: true,
    linkedIssue: false,
    ciPassed: true,
    aiSummary:
      "Replaced deprecated Docker client usage with Moby primitives and tightened the runtime path for deployment tooling.",
    evidenceSignals: ["Runtime code touched", "CI passed", "Infra module updated", "Maintainer review"],
  },
  {
    id: "pr-228",
    owner: "Ayush3941",
    repo: "gitrank",
    number: 228,
    title: "test: cover idempotent gateway sync",
    status: "merged",
    category: "Testing",
    difficultyScore: 63,
    impactScore: 74,
    reviewDepthScore: 66,
    testSignalScore: 92,
    repoWeight: 1.09,
    antiSpamMultiplier: 1,
    xpEarned: 504,
    additions: 214,
    deletions: 37,
    changedFilesCount: 8,
    mergedAt: "2026-04-20T08:12:00.000Z",
    maintainerReviewed: true,
    linkedIssue: true,
    ciPassed: true,
    aiSummary:
      "Added regression coverage around duplicate sync delivery and ensured replays do not double-apply state transitions.",
    evidenceSignals: ["Tests added", "Regression coverage", "Linked issue", "CI passed"],
  },
  {
    id: "pr-219",
    owner: "Ayush3941",
    repo: "gitrank",
    number: 219,
    title: "test: cover ledger replay recovery",
    status: "merged",
    category: "Testing",
    difficultyScore: 76,
    impactScore: 72,
    reviewDepthScore: 58,
    testSignalScore: 95,
    repoWeight: 1.14,
    antiSpamMultiplier: 1,
    xpEarned: 558,
    additions: 263,
    deletions: 18,
    changedFilesCount: 9,
    mergedAt: "2026-04-15T14:18:00.000Z",
    maintainerReviewed: false,
    linkedIssue: false,
    ciPassed: true,
    aiSummary:
      "Stress-tested replay recovery by asserting ledger consistency after interrupted ingestion cycles.",
    evidenceSignals: ["Tests added", "Resilience coverage", "CI passed", "Runtime pathways exercised"],
  },
  {
    id: "pr-213",
    owner: "Ayush3941",
    repo: "gitrank",
    number: 213,
    title: "fix: correct inverted tracing success attribute",
    status: "merged",
    category: "Bug Fix",
    difficultyScore: 57,
    impactScore: 69,
    reviewDepthScore: 51,
    testSignalScore: 61,
    repoWeight: 1.08,
    antiSpamMultiplier: 0.96,
    xpEarned: 331,
    additions: 42,
    deletions: 19,
    changedFilesCount: 3,
    mergedAt: "2026-04-08T07:42:00.000Z",
    maintainerReviewed: true,
    linkedIssue: true,
    ciPassed: true,
    aiSummary:
      "Fixed inverted tracing metadata that incorrectly labeled successful requests as failures in observability dashboards.",
    evidenceSignals: ["Bug fix", "Tracing code", "Maintainer review", "Linked issue"],
  },
  {
    id: "pr-207",
    owner: "Ayush3941",
    repo: "gitrank",
    number: 207,
    title: "docs: clarify runtime service access patterns",
    status: "open",
    category: "Documentation",
    difficultyScore: 45,
    impactScore: 55,
    reviewDepthScore: 29,
    testSignalScore: 12,
    repoWeight: 1,
    antiSpamMultiplier: 0.72,
    xpEarned: 112,
    additions: 89,
    deletions: 7,
    changedFilesCount: 4,
    mergedAt: "2026-05-04T09:00:00.000Z",
    maintainerReviewed: false,
    linkedIssue: false,
    ciPassed: true,
    aiSummary:
      "Clarifies access patterns between runtime services but is still waiting on maintainer review before earning full value.",
    evidenceSignals: ["Docs update", "Open PR", "CI passed"],
  },
];

const badges: Badge[] = [
  { id: "docs-architect", name: "Docs Architect", rarity: "Rare", description: "Earned from high-context documentation that changes contributor behavior.", unlockCondition: "Merge 3 documentation PRs with maintainer review.", icon: "scroll", unlocked: true, earnedAt: "2026-05-02", evidencePrIds: ["pr-241", "pr-207"], rarityScore: 68 },
  { id: "test-builder", name: "Test Builder", rarity: "Epic", description: "Signals repeated test depth on risky system paths.", unlockCondition: "Land 2 regression-heavy test PRs.", icon: "flask", unlocked: true, earnedAt: "2026-04-20", evidencePrIds: ["pr-228", "pr-219"], rarityScore: 82 },
  { id: "backend-signal-1", name: "Backend Signal I", rarity: "Uncommon", description: "Verified backend systems impact.", unlockCondition: "Reach 1,200 backend XP.", icon: "server", unlocked: true, earnedAt: "2026-04-14", evidencePrIds: ["pr-233", "pr-213"], rarityScore: 41 },
  { id: "review-grinder", name: "Review Grinder", rarity: "Rare", description: "Maintainers had to think with you, not after you.", unlockCondition: "Accumulate 6 deep review cycles.", icon: "messages", unlocked: true, earnedAt: "2026-05-01", evidencePrIds: ["pr-241", "pr-233", "pr-228"], rarityScore: 72 },
  { id: "infra-surgeon", name: "Infra Surgeon", rarity: "Epic", description: "Surgical infrastructure changes with low blast radius.", unlockCondition: "Merge one high-difficulty infrastructure PR.", icon: "wrench", unlocked: true, earnedAt: "2026-04-27", evidencePrIds: ["pr-233"], rarityScore: 84 },
  { id: "systems-builder", name: "Systems Builder", rarity: "Legendary", description: "Balanced signals across docs, tests, runtime, and architecture.", unlockCondition: "Reach level 25 with four skill tracks above 70.", icon: "crown", unlocked: true, earnedAt: "2026-05-03", evidencePrIds: ["pr-233", "pr-228", "pr-241"], rarityScore: 94 },
  { id: "consistent-contributor", name: "Consistent Contributor", rarity: "Rare", description: "A month of meaningful work without spammy drop-off.", unlockCondition: "Contribute across 4 active weeks.", icon: "calendar", unlocked: true, earnedAt: "2026-04-30", evidencePrIds: ["pr-213", "pr-219", "pr-228", "pr-241"], rarityScore: 70 },
  { id: "maintainer-signal-1", name: "Maintainer Signal I", rarity: "Epic", description: "Trusted enough that maintainers merge without defensive rewrites.", unlockCondition: "Land 5 maintainer-reviewed PRs at Gold tier.", icon: "shield", unlocked: false, progress: 72, evidencePrIds: ["pr-241", "pr-233", "pr-228", "pr-213"], rarityScore: 88 },
  { id: "performance-optimizer", name: "Performance Optimizer", rarity: "Legendary", description: "Reserved for measurable runtime wins.", unlockCondition: "Merge one performance PR with benchmark evidence.", icon: "bolt", unlocked: false, progress: 14, evidencePrIds: [], rarityScore: 92 },
  { id: "security-contributor", name: "Security Contributor", rarity: "Mythic", description: "Awarded only for security-sensitive fixes and review proof.", unlockCondition: "Land 2 reviewed security fixes with test coverage.", icon: "lock", unlocked: false, progress: 8, evidencePrIds: [], rarityScore: 99 },
];

const quests: Quest[] = [
  { id: "quest-security-review", title: "Ship one security-sensitive patch", description: "Target a permission, auth, or dependency-hardening issue to strengthen your weakest lane.", status: "Active", cadence: "Skill-based", rewardXp: 620, progress: 1, goal: 5, weakAreaTarget: "Security", whyRecommended: "Security is the lowest observed skill lane in this profile snapshot.", evidenceSignals: ["Security score 32", "No security badge unlocked", "Recent backend work suggests adjacent context"], linkedContributionIds: ["pr-233", "pr-213"] },
  { id: "quest-maintainer-review", title: "Merge one PR with maintainer review", description: "Push a contribution deep enough to trigger real maintainer feedback.", status: "Active", cadence: "Weekly", rewardXp: 320, progress: 2, goal: 3, whyRecommended: "Maintainer-reviewed PRs are the clearest trust signal for the current Gold tier.", evidenceSignals: ["4 reviewed PRs this window", "Review Grinder badge progress", "Gold III promotion path"], linkedContributionIds: ["pr-241", "pr-233", "pr-228"] },
  { id: "quest-docs-high-context", title: "Improve docs in a high-context repo", description: "Write docs that remove operational ambiguity for future contributors.", status: "Active", cadence: "Weekly", rewardXp: 280, progress: 6, goal: 10, weakAreaTarget: "Architecture", whyRecommended: "Documentation is already strong; this quest converts that strength into repeatable architecture signal.", evidenceSignals: ["Docs Architect badge earned", "Architecture score 78", "Recent runtime guide"], linkedContributionIds: ["pr-241", "pr-207"] },
  { id: "quest-regression-tests", title: "Add regression tests to one bug-fix PR", description: "Prove the failure and lock it down with tests.", status: "Completed", cadence: "Daily", rewardXp: 190, progress: 1, goal: 1, rewardBadgeId: "test-builder", whyRecommended: "The profile had high replay-risk work, so regression coverage created durable evidence.", evidenceSignals: ["Tests added", "Regression coverage", "CI passed"], linkedContributionIds: ["pr-228", "pr-219"] },
  { id: "quest-review-one-pr", title: "Review one open PR", description: "Comment on an open contribution with a concrete technical observation.", status: "Locked", cadence: "Daily", rewardXp: 110, progress: 0, goal: 1, weakAreaTarget: "Review", whyRecommended: "Unlocks after the profile has one more reviewed contribution to avoid low-context review farming.", evidenceSignals: ["Review score 61", "Needs more reciprocal review evidence"], linkedContributionIds: [] },
  { id: "quest-ci-improvement", title: "Add CI or build-system improvement", description: "Strengthen delivery paths instead of only touching product code.", status: "Active", cadence: "Long-term", rewardXp: 540, progress: 3, goal: 7, weakAreaTarget: "DevOps", whyRecommended: "Infra work is strong enough to turn into a delivery reliability lane.", evidenceSignals: ["Infra Surgeon badge earned", "DevOps score 64", "CI-passed infrastructure PR"], linkedContributionIds: ["pr-233"] },
];

const scoreChanges: ScoreBreakdown[] = [
  { label: "Merged runtime guide", deltaXp: 428, type: "gain", reason: "Maintainer-reviewed docs with high project context." },
  { label: "Infra client migration", deltaXp: 612, type: "gain", reason: "High difficulty infra change with CI confidence." },
  { label: "Open docs PR awaiting review", deltaXp: -38, type: "penalty", reason: "Open work earns reduced value until review depth is real." },
  { label: "Regression test coverage", deltaXp: 504, type: "gain", reason: "Tests reduced repeat failures in sync pathways." },
];

export const ayushProfile: UserProfile = {
  username: "Ayush3941",
  displayName: "Ayush Kumar Gaur",
  title: "Systems Builder",
  avatarUrl: "https://api.dicebear.com/9.x/glass/svg?seed=Ayush3941",
  bio: "Builds systems, improves runtime clarity, and treats maintainers like future teammates instead of merge bots.",
  gitRankScore: 88,
  mergedPrCount: 23,
  reviewedPrCount: 17,
  bestCategory: "Backend",
  consistencyScore: 91,
  strongestSignals: ["Documentation", "Backend", "Testing", "Architecture"],
  topSkills: ["Documentation", "Backend", "Testing"],
  level: { currentLevel: 27, title: "Systems Builder", currentXp: 7840, nextLevelXp: 9000, rankTier: "Gold III" },
  rankProgress: {
    season: currentSeason,
    currentTier: "Gold III",
    nextTier: "Platinum I",
    seasonXp: 1164,
    xpToNextTier: 1160,
    promotionCutoffRank: 25,
    safetyCutoffRank: 75,
    evidenceSignals: ["Maintainer-reviewed PRs", "Regression tests", "High-context docs"],
  },
  skillTree: [
    { category: "Documentation", score: 86, delta: 8, note: "High-context service guides and operational docs." },
    { category: "Testing", score: 83, delta: 11, note: "Regression coverage around replay and sync edges." },
    { category: "Backend", score: 81, delta: 9, note: "Runtime fixes and service ownership patterns." },
    { category: "Frontend", score: 28, delta: 3, note: "Limited signal so far." },
    { category: "DevOps", score: 64, delta: 7, note: "Infra cleanup and delivery path care." },
    { category: "Security", score: 32, delta: 2, note: "Weakest lane and best quest target." },
    { category: "Performance", score: 39, delta: 1, note: "No strong benchmark-backed wins yet." },
    { category: "Architecture", score: 78, delta: 6, note: "Cross-service reasoning shows up in docs and infra work." },
    { category: "Review", score: 61, delta: 5, note: "Maintainer interaction depth is rising." },
  ],
  contributions: [...contributions],
  badges,
  quests,
  scoreChanges,
  xpTimeline: [
    { label: "Mar 31", xp: 4320 },
    { label: "Apr 07", xp: 4651 },
    { label: "Apr 14", xp: 5209 },
    { label: "Apr 21", xp: 5713 },
    { label: "Apr 28", xp: 6325 },
    { label: "May 05", xp: 7840 },
  ],
  syncStatus: { state: "stale", lastSyncedAt: "2026-04-29T16:25:00.000Z", currentStep: "Awaiting next GitHub sync", progress: 100, partialProfileAvailable: true },
  weeklyXp: 1164,
  leaguePosition: 42,
  movement: 7,
  repositories: [
    { name: "Ayush3941/gitrank", tracked: true, visibility: "Public", reason: "Core public portfolio project." },
    { name: "Ayush3941/core-stack-backend", tracked: true, visibility: "Public", reason: "High-signal backend collaboration." },
    { name: "Ayush3941/fabric-smart-client", tracked: false, visibility: "Hidden", reason: "Keep niche experiments off the public card." },
  ],
  privacy: {
    publicProfileEnabled: true,
    showExactPRs: true,
    showAiSummaries: true,
    showLeaderboardParticipation: true,
    badgeUnlockedNotifications: true,
    levelUpNotifications: true,
    weeklyReportNotifications: false,
    reducedGamification: false,
  },
};

export const prAnalyses: PullRequestAnalysis[] = ayushProfile.contributions.map((contribution) => ({
  contribution,
  baseValue: Math.round(contribution.difficultyScore * 2.8),
  mergedBonus: contribution.status === "merged" ? 90 : 18,
  reviewBonus: Math.round(contribution.reviewDepthScore * 1.2),
  testBonus: Math.round(contribution.testSignalScore * 0.9),
  repoBonus: Math.round((contribution.repoWeight - 1) * 180),
  aiConfidence: contribution.status === "open" ? 0.78 : 0.92,
  scoreComponents: [
    {
      key: "preview_only",
      label: "Preview-only sample",
      value: contribution.xpEarned,
      displayValue: `${contribution.xpEarned} XP`,
      source: "dev_preview_fixture",
      reason: "Development-only preview data is isolated from production routes.",
    },
  ],
  badgeUnlocks: [],
  penalties:
    contribution.status === "open"
      ? [{ label: "Pending maintainer verification", deltaXp: -48, type: "penalty", reason: "Open PRs receive reduced trust until review depth is known." }]
      : [],
  suggestedQuestId:
    contribution.category === "Documentation" ? "quest-maintainer-review" : "quest-security-review",
}));

const baseLeaderboard: LeaderboardEntry[] = [
  { rank: 1, username: "maintainer_monk", displayName: "Shivangi Rao", title: "Runtime Cartographer", rankTier: "Diamond", weeklyXp: 1880, totalXp: 12640, movement: 1, focus: "Architecture", division: "Diamond Arena", seasonXp: 1880, xpToNextRank: 0, promotionZone: true, demotionRisk: false, evidenceSummary: "Architecture-heavy reviewed PRs with sustained repo impact.", scoreFormulaVersion: currentSeason.scoringVersion },
  { rank: 2, username: "byteharvest", displayName: "Rohit Sen", title: "Build Tactician", rankTier: "Platinum I", weeklyXp: 1604, totalXp: 11980, movement: -1, focus: "DevOps", division: "Platinum Crucible", seasonXp: 1604, xpToNextRank: 277, promotionZone: true, demotionRisk: false, evidenceSummary: "CI and deployment work with high delivery-path signal.", scoreFormulaVersion: currentSeason.scoringVersion },
  { rank: 3, username: "ayesha-tests", displayName: "Ayesha Khan", title: "Regression Marshal", rankTier: "Platinum I", weeklyXp: 1542, totalXp: 11040, movement: 2, focus: "Testing", division: "Platinum Crucible", seasonXp: 1542, xpToNextRank: 63, promotionZone: true, demotionRisk: false, evidenceSummary: "Regression coverage and maintainer-reviewed test depth.", scoreFormulaVersion: currentSeason.scoringVersion },
  { rank: 42, username: "Ayush3941", displayName: "Ayush Kumar Gaur", title: "Systems Builder", rankTier: "Gold III", weeklyXp: 1164, totalXp: 7840, movement: 7, focus: "Backend", isCurrentUser: true, division: "Gold Forge", seasonXp: 1164, xpToNextRank: 379, promotionZone: false, demotionRisk: false, evidenceSummary: "Backend, docs, and regression evidence across the active season.", scoreFormulaVersion: currentSeason.scoringVersion },
  { rank: 43, username: "samdocs", displayName: "Samir Das", title: "Docs Forger", rankTier: "Gold III", weeklyXp: 1128, totalXp: 7765, movement: 3, focus: "Documentation", division: "Gold Forge", seasonXp: 1128, xpToNextRank: 37, promotionZone: false, demotionRisk: false, evidenceSummary: "Documentation-heavy PRs with clear reviewer context.", scoreFormulaVersion: currentSeason.scoringVersion },
];

export const leaderboardByTab: Record<string, LeaderboardEntry[]> = {
  Global: baseLeaderboard,
  India: baseLeaderboard,
  College: baseLeaderboard.slice(2),
  Backend: baseLeaderboard.slice().sort((a, b) => b.totalXp - a.totalXp),
  Testing: baseLeaderboard.slice().sort((a, b) => b.weeklyXp - a.weeklyXp),
  Documentation: baseLeaderboard.slice().reverse(),
  "Weekly XP": baseLeaderboard.slice().sort((a, b) => b.weeklyXp - a.weeklyXp),
  "Rising Contributors": baseLeaderboard.slice().sort((a, b) => b.movement - a.movement),
};

export const leaderboardSnapshots: Record<string, LeaderboardSnapshot> = Object.fromEntries(
  Object.entries(leaderboardByTab).map(([tab, rows]) => [
    tab,
    {
      season: currentSeason,
      rows,
      currentUser: rows.find((row) => row.isCurrentUser),
    },
  ]),
);

export const dashboardData: DashboardData = {
  user: ayushProfile,
  recentReports: prAnalyses.slice(0, 4),
};
