#!/usr/bin/env sh
set -eu

repo_value="${GITHUB_REPOSITORY:-}"
inferred_repo_value="${INFERRED_GITHUB_REPOSITORY:-}"

if [ -n "$repo_value" ]; then
  printf 'GITHUB_REPOSITORY=set\n'
elif [ -n "$inferred_repo_value" ]; then
  printf 'GITHUB_REPOSITORY=set(inferred:%s)\n' "$inferred_repo_value"
else
  printf 'GITHUB_REPOSITORY=unset\n'
fi

for var_name in \
  GITRANK_REPO_ADMIN_TOKEN \
  GITHUB_TOKEN \
  GH_TOKEN \
  GITHUB_APP_ID \
  GITHUB_APP_INSTALLATION_ID \
  GITHUB_APP_PRIVATE_KEY_FILE \
  GITHUB_APP_PRIVATE_KEY_PEM \
  GITRANK_GITHUB_APP_ID \
  GITRANK_GITHUB_APP_INSTALLATION_ID \
  GITRANK_GITHUB_APP_PRIVATE_KEY_FILE \
  GITRANK_GITHUB_APP_PRIVATE_KEY_PEM \
  PROMETHEUS_BASE_URL \
  GRAFANA_BASE_URL \
  GRAFANA_API_TOKEN \
  OBS_EVIDENCE_FILE \
  ROLLBACK_EVIDENCE_FILE \
  RESTORE_EVIDENCE_FILE \
  IMAGE_TAG \
  IMAGE_REGISTRY_OWNER \
  REQUIRE_ENV_SPECIFIC_K8S_OVERRIDES \
  STAGING_K8S_PUBLIC_BASE_URL \
  PRODUCTION_K8S_PUBLIC_BASE_URL \
  STAGING_K8S_API_BASE_URL \
  PRODUCTION_K8S_API_BASE_URL \
  STAGING_K8S_AUTH_COOKIE_DOMAIN \
  PRODUCTION_K8S_AUTH_COOKIE_DOMAIN \
  STAGING_K8S_GITHUB_OAUTH_REDIRECT_URL \
  PRODUCTION_K8S_GITHUB_OAUTH_REDIRECT_URL \
  STAGING_K8S_API_HOST \
  PRODUCTION_K8S_API_HOST \
  STAGING_K8S_AUTH_HOST \
  PRODUCTION_K8S_AUTH_HOST \
  STAGING_K8S_TLS_SECRET_NAME \
  PRODUCTION_K8S_TLS_SECRET_NAME
do
  eval var_value="\${$var_name-}"
  if [ -n "$var_value" ]; then
    printf '%s=set\n' "$var_name"
  else
    printf '%s=unset\n' "$var_name"
  fi
done
