apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitrank
spec:
  tls:
    - hosts:
        - api.gitrank.example.com
        - auth.gitrank.example.com
      secretName: gitrank-production-tls
  rules:
    - host: api.gitrank.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  name: http
    - host: auth.gitrank.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  name: http
