#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_FILE="${1:-$ROOT_DIR/docs/REPO_TREE.md}"
MAX_DEPTH="${MAX_DEPTH:-2}"

render_tree() {
  local tracked_files
  tracked_files="$(
    cd "$ROOT_DIR"
    git ls-files | while IFS= read -r file; do
      [[ -e "$file" ]] && printf '%s\n' "$file"
    done
  )"

  if command -v tree >/dev/null 2>&1; then
    printf '%s\n' "$tracked_files" \
      | tree --fromfile -L "$MAX_DEPTH" --dirsfirst --noreport .
    return 0
  fi

  printf '%s\n' "$tracked_files" \
    | awk -v max_depth="$MAX_DEPTH" '
      {
        path=""
        for (i = 1; i <= NF && i <= max_depth; i++) {
          if (path == "") {
            path = $i
          } else {
            path = path "/" $i
          }
          seen[path] = 1
        }
      }
      END {
        for (entry in seen) {
          print "./" entry
        }
      }
    ' FS='/' \
    | sort
}

mkdir -p "$(dirname "$OUTPUT_FILE")"

{
  printf '# Repository Tree\n\n'
  printf 'Generated by `scripts/generate-repo-tree.sh`.\n\n'
  printf '```text\n'
  render_tree
  printf '```\n'
} >"$OUTPUT_FILE"

printf 'wrote %s\n' "$OUTPUT_FILE"
